### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by Emustclose** [N238635/node-SteamMarketBot#3]
Добрый день, возможно я что-то не так понял с установкой ,но при запуске _node passiveBot.js_  выдает ошибку _Error: Cannot find module './config.json'_ , подскажите где я могу найти этот файл или как решить эту проблему?

**Comment by N238635** [comment]
Проект выложен для учебно-ознакомительных целей. Запускать его без понимания как он работает я не советую, т.к. он БУДЕТ тратить деньги на аккаунте.
